# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
