# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackernews', '0002_auto_20151224_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 16, 2, 55, 968533, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentvote',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 16, 5, 43, 481307, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 16, 5, 49, 755377, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvote',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 16, 5, 55, 105395, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
