# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_auto_20151228_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='user',
        ),
    ]
